# Generated by Django 2.2.2 on 2019-07-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(height_field=150, upload_to='', width_field=150)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
