# Generated by Django 2.2.2 on 2019-07-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(height_field=150, upload_to='images/', width_field=150),
        ),
    ]
